export const BLACK = "\x1b[30m";    export const black = "\x1b[30m"
export const RED = "\x1b[31m";      export const red = "\x1b[31m"
export const GREEN = "\x1b[32m";    export const green = "\x1b[32m"
export const YELLOW = "\x1b[33m";   export const yellow = "\x1b[33m"
export const BLUE = "\x1b[34m";     export const blue = "\x1b[34m"
export const MAGENTA = "\x1b[35m";  export const magenta = "\x1b[35m"
export const CYAN = "\x1b[36m";     export const cyan = "\x1b[36m"
export const WHITE = "\x1b[37m";    export const white = "\x1b[37m"